
name: keg-format
on:
  push:
    branches:
      - develop

jobs:
  tests:
    name: 'Format Repo Code'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Get Changed Files"
        id: get-changed-files
        run: bash scripts/ci/getChangedFiles.sh

      - name: "Get Changed Repos"
        id: get-changed-repos
        run: bash scripts/ci/getChangedRepos.sh

      - name: "Install Yarn Dependencies"
        id: install-yarn-dependencies
        run: bash scripts/ci/runYarnCmd.sh "install"

      - name: "Run Repo Format"
        id: run-repo-format
        run: bash scripts/ci/runYarnCmd.sh "format"

      - name: "Commit Repo Changes"
        id: commit-changes
        run: bash scripts/ci/commitChanges.sh "Repo-Format"
